dist: jammy
sudo: required
language: python
python:
  - "pypy"
  - "pypy3"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
before_install:
  - git clone https://github.com/buffer/libemu.git
  - cd libemu
  - autoreconf -v -i
  - ./configure
  - sudo make install
  - cd -
install:
  - sudo python setup.py install
script:
  - echo "Build done"
